{% set name = "pynmeagps" %}
{% set version = "1.0.45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynmeagps-{{ version }}.tar.gz
  sha256: 92ef4c2c1d15a19a37ff55af3a3458e9c29f58f6ca88813900198830a6ab3a3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pynmeagps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/semuconsulting/pynmeagps
  description: Python library for parsing and generating NMEA 0183 GNSS protocol messages.
  summary: NMEA protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pynmeagps/
  dev_url: https://github.com/semuconsulting/pynmeagps

extra:
  recipe-maintainers:
    - semuadmin
