{% set name = "pynmeagps" %}
{% set version = "1.0.52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynmeagps-{{ version }}.tar.gz
  sha256: 270fd0694ed7ca86d7cd85e5f0109b9ce48aceee5b6c8d417a40966f28460bb9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pynmeagps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/semuconsulting/pynmeagps
  description: Python library for parsing and generating NMEA 0183 GNSS protocol messages.
  summary: NMEA protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pynmeagps/
  dev_url: https://github.com/semuconsulting/pynmeagps

extra:
  recipe-maintainers:
    - semuadmin
